version: '2.2'
services:
  Allen:
    image: grpc
    ports:
      - "4000:4000"
    networks:
      - proxynet
    environment:
      - ADD_PORT=4000
      - FRND_PORT=5000
      - USER=Allen
      - CONNECTION_ADD=Bob
  Bob:
    image: grpc
    ports:
      - "5000:5000"
    networks:
      - proxynet
    environment:
      - ADD_PORT=5000
      - FRND_PORT=4000
      - USER=Bob 
      - CONNECTION_ADD=Allen  
networks:
  proxynet:
    driver: bridge